### ISSUE TITLE
Add Embrace to Adopters from SoCal Meetup on 8/21

### ISSUE THREAD

**Issue by MarieAsg** [ClickHouse/clickhouse-docs#2650] opened 2024-09-20 22:03 UTC
[How Embrace uses ClickHouse  (Meetup 2024-08-21) (1).pptx](https://github.com/user-attachments/files/17081149/How.Embrace.uses.ClickHouse.Meetup.2024-08-21.1.pptx)

**Comment by gingerwizard** [comment] 2024-12-10 10:56
Duplicate of https://github.com/ClickHouse/clickhouse-docs/issues/2650

**Closed by gingerwizard** 2024-12-10 10:56 UTC
Labels: adopters
