### ISSUE TITLE
Document `analysisOfVariance` function.

### ISSUE THREAD

**Issue by johnnymatthews** [ClickHouse/clickhouse-docs#1930] opened 2024-02-11 18:55 UTC
Create documentation for the `analysisOfVariance` function. See #1833 for details on how to complete this issue.

Child issue of #1833.

**Comment by Blargian** [comment] 2024-05-17 06:55
[#1932](https://github.com/ClickHouse/clickhouse-docs/issues/1932) is a duplicate of this issue as `anova` is the alias.

**Closed** 2024-05-21 06:06 UTC
Labels: functions-project
