### ISSUE TITLE
Add experimental docs about transactions

### ISSUE THREAD

**Issue by tbragin** [ClickHouse/clickhouse-docs#888] opened 2023-03-09 16:23 UTC
Per @alexey-milovidov  It's ok to document transactions as an experimental feature, with explicit call out of functional limitations (e.g. that it does not work with replicated MergeTree engines)

Some source docs / examples here https://presentations.clickhouse.com/release_22.4/

**Comment by DanRoscigno** [comment] 2023-04-11 19:19
https://github.com/ClickHouse/ClickHouse/issues/22086 is a bit outdated, but still relevant. For example, mintid/maxtid were renamed to creation_tid/removal_tid, but the overall idea is almost the same. Although, this issue is mostly about internal implementation details, there are important notes about isolation and durability guarantees (tl;dr: durability is not guaranteed (and probably will never be) with default settings; isolation level is "snapshot isolation" unless you combine transactional and non-transactional queries, transactional mutations are too heavy and often roll back due to conflicts).

There are some tests that can be used as examples:

Simple tests (good for basic understanding):
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01173_transaction_control_queries.sql
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/02345_implicit_transaction.sql
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01172_transaction_counters.sql
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01167_isolation_hermitage.sh

More complex tests:
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01170_alter_partition_isolation.sh
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01171_mv_select_insert_isolation_long.sh
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01174_select_insert_isolation.sh
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01168_mutations_isolation.sh
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01169_alter_partition_isolation_stress.sh
https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_transactions/test.py

For introspection, we have:
- system.transactions table (shows info about running transactions, like system.processes) 
- system.transaction_info_log  (shows changes history), 
- creation/removal_tid/csn and is_visible columns in system.parts  
- and a set of functions (transactionID , transactionLatestSnapshot , transactionOldestSnapshot )

TIDs, CSNs and reserved values with special meaning:
https://github.com/ClickHouse/ClickHouse/blob/0719d01d39ae3e2853f67f67d53cc77028377584/src/Common/TransactionID.h#L22-L55
https://github.com/ClickHouse/ClickHouse/blob/0719d01d39ae3e2853f67f67d53cc77028377584/src/Common/TransactionID.h#L94-L96

There's a quite tricky setting wait_changes_become_visible_after_commit_mode. Due to some implementation details, new changes do not become visible immediately after the COMMIT statement returns. COMMIT statement waits for the committed changes to become actually visible if it's set to WAIT. SYSTEM SYNC TRANSACTION LOG does the same. Also, COMMIT may throw UNKNOWN_STATUS_OF_TRANSACTION if the ZooKeeper connection was lost during committing. But it waits for the connection to be recovered and obtains actual commit status if the setting is set to WAIT_UNKNOWN (default).

Currently, transactions work with non-replicated MergeTree tables only. The feature is experimental and backward compatibility can be broken.

**Comment by DanRoscigno** [comment] 2023-04-12 17:33
Requirements:
- ClickHouse Keeper or ZooKeeper to track transactions
- Atomic DB only (Default)
- Non-Replicated MergeTree table engine only
- Enable experimental setting in `config.d/transactions.xml`:
  ```
  <clickhouse>
    <allow_experimental_transactions>1</allow_experimental_transactions>
  </clickhouse>
  ```

**Comment by DanRoscigno** [comment] 2023-04-12 17:44
Notes:
- This is an experimental feature, and changes should be expected.
- If an exception occurs during a transaction, you cannot commit the transaction.  This includes all exceptions, including `UNKNOWN_FUNCTION` exceptions caused by typos.  
- Nested transactions are not supported; finish the current transaction and start a new one instead

**Comment by DanRoscigno** [comment] 2023-04-12 20:26
Rough run through of some queries from CI test
```sql
❯ docker compose exec clickhouse-01 clickhouse-client
ClickHouse client version 23.3.1.2823 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.3.1 revision 54462.

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: 867fe904-9f64-41a6-a007-3c75e18f304d

Ok.

0 rows in set. Elapsed: 0.017 sec. 

cluster_1S_2R node 1 :) rollback;

ROLLBACK

Query id: d09378f8-62ce-440e-aabe-9f33c91c7d74

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) create table mt1 (n Int64) engine=MergeTree order by n;

CREATE TABLE mt1
(
    `n` Int64
)
ENGINE = MergeTree
ORDER BY n

Query id: ecc950a7-8f37-4b76-a9fe-433361dab063

Ok.

0 rows in set. Elapsed: 0.012 sec. 

cluster_1S_2R node 1 :) create table mt2 (n Int64) engine=MergeTree order by n;

CREATE TABLE mt2
(
    `n` Int64
)
ENGINE = MergeTree
ORDER BY n

Query id: aad44c03-df8c-4442-997e-af61f3aeb556

Ok.

0 rows in set. Elapsed: 0.012 sec. 

cluster_1S_2R node 1 :) commit;

COMMIT

Query id: fd1aa7fb-09be-4468-afff-a99087131a29


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.3.1):
Code: 649. DB::Exception: Received from localhost:9000. DB::Exception: There is no current transaction. (INVALID_TRANSACTION)

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: 34489a96-59e1-4697-9fb7-0a4342b3178f

Ok.

0 rows in set. Elapsed: 0.000 sec. 

cluster_1S_2R node 1 :) insert into mt1 values (1);

INSERT INTO mt1 FORMAT Values

Query id: a4cb2090-74c5-4573-93d0-119c1f49e734

Ok.

1 row in set. Elapsed: 0.013 sec. 

cluster_1S_2R node 1 :) insert into mt2 values (10);

INSERT INTO mt2 FORMAT Values

Query id: b7e9959f-c98f-46aa-ac88-cf140d2e41b6

Ok.

1 row in set. Elapsed: 0.013 sec. 

cluster_1S_2R node 1 :) select 'commit', arraySort(groupArray(n)) from (select n from mt1 union all select * from mt2);

SELECT
    'commit',
    arraySort(groupArray(n))
FROM
(
    SELECT n
    FROM mt1
    UNION ALL
    SELECT *
    FROM mt2
)

Query id: dae0e81c-8039-4cb8-953f-ce69b6fc4c4c

┌─'commit'─┬─arraySort(groupArray(n))─┐
│ commit   │ [1,10]                   │
└──────────┴──────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

cluster_1S_2R node 1 :) commit;

COMMIT

Query id: af217911-081f-4ae3-bcef-0d893dd8e815

Ok.

0 rows in set. Elapsed: 0.042 sec. 

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: 405242ee-112f-416c-ba6b-240f3ebd6671

Ok.

0 rows in set. Elapsed: 0.000 sec. 

cluster_1S_2R node 1 :) insert into mt1 values (2);

INSERT INTO mt1 FORMAT Values

Query id: 367c8319-d634-414b-ac49-a2d0d4bf44d5

Ok.

1 row in set. Elapsed: 0.012 sec. 

cluster_1S_2R node 1 :) insert into mt2 values (20);

INSERT INTO mt2 FORMAT Values

Query id: 6e2768b5-6680-4368-a5d1-2acec08d1c77

Ok.

1 row in set. Elapsed: 0.012 sec. 

cluster_1S_2R node 1 :) select 'rollback', arraySort(groupArray(n)) from (select n from mt1 union all select * from mt2);

SELECT
    'rollback',
    arraySort(groupArray(n))
FROM
(
    SELECT n
    FROM mt1
    UNION ALL
    SELECT *
    FROM mt2
)

Query id: c25a53d1-f311-4803-971b-9e5d1d919ee4

┌─'rollback'─┬─arraySort(groupArray(n))─┐
│ rollback   │ [1,2,10,20]              │
└────────────┴──────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

cluster_1S_2R node 1 :) rollback;

ROLLBACK

Query id: 5a0069ba-0abd-43a5-bacb-b75c2c730507

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: 56a83312-782a-4d73-8770-4b333843ed3e

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) select 'no nested', arraySort(groupArray(n)) from (select n from mt1 union all select * from mt2);

SELECT
    'no nested',
    arraySort(groupArray(n))
FROM
(
    SELECT n
    FROM mt1
    UNION ALL
    SELECT *
    FROM mt2
)

Query id: 1a3e9059-6f22-43d0-80db-6f407eb8ec20

┌─'no nested'─┬─arraySort(groupArray(n))─┐
│ no nested   │ [1,10]                   │
└─────────────┴──────────────────────────┘

1 row in set. Elapsed: 0.004 sec. 

cluster_1S_2R node 1 :) begin transaction; -- { serverError INVALID_TRANSACTION }

BEGIN TRANSACTION

Query id: cf80c3c1-670c-45ef-a1aa-6d4a9f9150d5


0 rows in set. Elapsed: 0.002 sec. 

Received exception from server (version 23.3.1):
Code: 649. DB::Exception: Received from localhost:9000. DB::Exception: Nested transactions are not supported. (INVALID_TRANSACTION)

cluster_1S_2R node 1 :) rollback;

ROLLBACK

Query id: c695c12d-d473-4947-b74d-d803736ff2a5

Ok.

0 rows in set. Elapsed: 0.000 sec. 

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: 1aae4202-f4f8-4330-986b-591a78d87354

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) insert into mt1 values (3);

INSERT INTO mt1 FORMAT Values

Query id: 4b3e8ccd-5243-453b-b4cc-00d283054d33

Ok.

1 row in set. Elapsed: 0.012 sec. 

cluster_1S_2R node 1 :) insert into mt2 values (30);

INSERT INTO mt2 FORMAT Values

Query id: af848037-0f47-4acc-8bea-e6a57f7e6a89

Ok.

1 row in set. Elapsed: 0.011 sec. 

cluster_1S_2R node 1 :) select 'on exception before start', arraySort(groupArray(n)) from (select n from mt1 union all select * from mt2);

SELECT
    'on exception before start',
    arraySort(groupArray(n))
FROM
(
    SELECT n
    FROM mt1
    UNION ALL
    SELECT *
    FROM mt2
)

Query id: 5fcf1ab0-11bb-4bf5-ab64-65871727de9c

┌─'on exception before start'─┬─arraySort(groupArray(n))─┐
│ on exception before start   │ [1,3,10,30]              │
└─────────────────────────────┴──────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

cluster_1S_2R node 1 :) select functionThatDoesNotExist(); -- { serverError 46 }

SELECT functionThatDoesNotExist()

Query id: 5f73042d-b876-4129-9461-72f2c3e1670a


0 rows in set. Elapsed: 0.005 sec. 

Received exception from server (version 23.3.1):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function functionThatDoesNotExist: While processing functionThatDoesNotExist(). (UNKNOWN_FUNCTION)

cluster_1S_2R node 1 :) commit;

COMMIT

Query id: 9040e1d7-52eb-41a5-a696-f2b81a258e1e


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.3.1):
Code: 649. DB::Exception: Received from localhost:9000. DB::Exception: Transaction is not in RUNNING state. (INVALID_TRANSACTION)

cluster_1S_2R node 1 :) rollback;

ROLLBACK

Query id: e8c63fa4-bdc0-4f85-8911-bc6bdb4a0c39

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) insert into mt1 values (4);

INSERT INTO mt1 FORMAT Values

Query id: b845e33f-f118-4f5b-92ee-fde0d798f16d

Ok.

1 row in set. Elapsed: 0.003 sec. 

cluster_1S_2R node 1 :) insert into mt2 values (40);

INSERT INTO mt2 FORMAT Values

Query id: c980e4ad-4bfc-4cf8-bd4c-a7eadbe5bd9a

Ok.

1 row in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) select 'on exception while processing', arraySort(groupArray(n)) from (select n from mt1 union all select * from mt2);

SELECT
    'on exception while processing',
    arraySort(groupArray(n))
FROM
(
    SELECT n
    FROM mt1
    UNION ALL
    SELECT *
    FROM mt2
)

Query id: e60e6936-3d28-4371-a594-8abee276b0e2

┌─'on exception while processing'─┬─arraySort(groupArray(n))─┐
│ on exception while processing   │ [1,4,10,40]              │
└─────────────────────────────────┴──────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

cluster_1S_2R node 1 :) select throwIf(100 < number) from numbers(1000); -- { serverError 395 }

SELECT throwIf(100 < number)
FROM numbers(1000)

Query id: 9b243228-8b5c-41c9-b410-77b245b40d93


0 rows in set. Elapsed: 0.012 sec. 

Received exception from server (version 23.3.1):
Code: 395. DB::Exception: Received from localhost:9000. DB::Exception: Value passed to 'throwIf' function is non-zero: while executing 'FUNCTION throwIf(less(100, number) :: 2) -> throwIf(less(100, number)) UInt8 : 0'. (FUNCTION_THROW_IF_VALUE_IS_NON_ZERO)

cluster_1S_2R node 1 :) rollback

ROLLBACK

Query id: 99af3f9f-f28c-4ebe-97ab-1d8d319091d5


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.3.1):
Code: 649. DB::Exception: Received from localhost:9000. DB::Exception: There is no current transaction. (INVALID_TRANSACTION)

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: aa22e491-88d6-44f1-bd61-fa6761c15327

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) insert into mt1 values (6);

INSERT INTO mt1 FORMAT Values

Query id: 04b171e9-f3dc-46b6-94d4-342f78728930

Ok.

1 row in set. Elapsed: 0.013 sec. 

cluster_1S_2R node 1 :) insert into mt2 values (60);

INSERT INTO mt2 FORMAT Values

Query id: 38feea3d-7c3a-4f12-98f7-2ebf8bf082ca

Ok.

1 row in set. Elapsed: 0.012 sec. 

cluster_1S_2R node 1 :) select 'on session close', arraySort(groupArray(n)) from (select n from mt1 union all select * from mt2);

SELECT
    'on session close',
    arraySort(groupArray(n))
FROM
(
    SELECT n
    FROM mt1
    UNION ALL
    SELECT *
    FROM mt2
)

Query id: 2c4d5e7f-4d8d-4dc7-9c71-9842e3f3bd8f

┌─'on session close'─┬─arraySort(groupArray(n))─┐
│ on session close   │ [1,4,6,10,40,60]         │
└────────────────────┴──────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

cluster_1S_2R node 1 :) rollback

ROLLBACK

Query id: 9393ef49-a0ce-444f-ae11-e93a322ef1ab

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) create table m (n int) engine=Memory;

CREATE TABLE m
(
    `n` int
)
ENGINE = Memory

Query id: 71c319bd-357b-437d-96bf-754d6f1fcbda

Ok.

0 rows in set. Elapsed: 0.011 sec. 

cluster_1S_2R node 1 :) begin transaction;

BEGIN TRANSACTION

Query id: c1f56061-9c3d-4e1b-9deb-9ae8f0fc93d9

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) insert into m values (1);

INSERT INTO m FORMAT Values

Query id: 9723bd08-e605-4955-babd-4563b8f20d60


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.3.1):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Storage Memory (table default.m (521a673d-4403-4655-8c49-463eff595a3e)) does not support transactions. (NOT_IMPLEMENTED)

cluster_1S_2R node 1 :) rollback

ROLLBACK

Query id: 7cc4ed6d-675e-446e-b1ee-75e746395569

Ok.

0 rows in set. Elapsed: 0.001 sec. 

cluster_1S_2R node 1 :) select functionThatDoesNotExist();

SELECT functionThatDoesNotExist()

Query id: 3bfd86af-f478-4f3d-9dc4-c4cdbfb4cef6


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.3.1):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function functionThatDoesNotExist: While processing functionThatDoesNotExist(). (UNKNOWN_FUNCTION)

```

**Closed** 2023-04-20 18:15 UTC
